before_script:
- psql -c 'create database photob;' -U postgres

language: python

python:
- "2.7"

env:
- DJANGO=1.4 DB=postgres TRAVIS=true FACEBOOK_APP_ID=string FACEBOOK_API_SECRET=string

install:
- "pip install -q DJANGO==$DJANGO --use-mirrors"
- "pip install -q -r requirements.txt --use-mirrors"

script: python manage.py test


